# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test111111():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_111111(self):
    self.driver.get("https://qa.neapro.site/cabinet/documents")
    self.driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(1) > img").click()
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.XPATH, "//div[6]/div/div/div/input").send_keys("(___)___-__ __")
    self.driver.find_element(By.CSS_SELECTOR, ".form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".vue-dadata__input").send_keys("Волгоградская обл")
    element = self.driver.find_element(By.ID, "phone")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
